### ISSUE TITLE
Question:Login component like view layer example?

### ISSUE THREAD

**Issue by Valexr** [arlac77/svelte-session-manager#439]
I understand correctly — Login.svelte component like view layer example?

**Comment by arlac77** [comment]
In 'tests/app/src/App.svelte' You can see

the session creation

```js
export const session = new Session(localStorage);
```

and the use of a form to refresh (login) the session:

```js
<Login {session} endpoint="/api/login" {result}>
</Login>
```

**Comment by Valexr** [comment]
Yep! & I can make my form instead <Login> ?

**Comment by arlac77** [comment]
Simply call

```js
await login(session, endpoint, username, password);
```

from your form

**Comment by Valexr** [comment]
Ok. Thx 😊
