### ISSUE TITLE
What is the $values in readme?

### ISSUE THREAD

**Issue by Valexr** [arlac77/svelte-session-manager#467]
Can you explain me about `$values` & what is this fetch url `https://mydomain.com/values`?
I thinking about checkout /update by refresh_tokens strategy...

```js 
!session.isValid
``` 
if expire access_token, but i'm also have refresh_token & how i can check this on client & set new acces_token without 

```js
login(...args, name, pass)
```

& how i can use initialized in Login component 
```js
session = new Session(sessionStorage)
```
 in other components?

**Comment by Valexr** [comment]
i'm found update() & save() session methods & it's usefull, but i think needs one more method seem like `login()` but without user.password — `refresh(refresh_token, fetch_url, session.authorizationHeader)` & on server verify token & return new access/refresh_tokens to session storage. i made this manually with session.update() & session.save() functions, but...🤓 single method may be more usefull

**Comment by Valexr** [comment]
& how check when expires refresh_token ?

**Comment by arlac77** [comment]
Currently there is no refresh_token logic implemented.
Probably the should be a timer to execute the refresh by itself.
I You like we can work out the implementation.

**Comment by Valexr** [comment]
it's cool upgrade I think... but I'm just using yours `Session` class )))

**Comment by Valexr** [comment]
& I didn't find `res.status` in `login()` function — it's may be useful for client logic😉

**Comment by Valexr** [comment]
& I didn't find `res.status` code & my custom messages from server in callback `login()` function — it's may be useful for client logic😉

**Comment by Valexr** [comment]
Now I’m ping server by refersh_token:

```js
jwt.verify.ok ? session.update(access_token) : session.invalidate()
```
