### ISSUE TITLE
q:  How i can dinamicly change backing session store?

### ISSUE THREAD

**Issue by Valexr** [arlac77/svelte-session-manager#469]
Something like:

```js
$: save = some boolean conditions...( true/false )

const session = new Session(save ? localStorage : sessionStorage)
```

**Comment by arlac77** [comment]
with [cf6fd9fa611a82b95c781107eaa058477bf4ec78](https://github.com/arlac77/svelte-session-manager/commit/cf6fd9fa611a82b95c781107eaa058477bf4ec78) released in 1.4.0 You can
```js
const session = new Session(localStorage)


// later
session.store = sessionStorage;
```

But be aware the currently the content of the former store will not be transferred to the new store

**Comment by Valexr** [comment]
Tx very much🤓now I can use remember checkbox 👍🏻for localStorage. & I don’t need dynamically change back store, just on authentication when initialise session.

**Comment by Valexr** [comment]
Testing. Not working for me:
in login endpoint middleware I trying before fetch set store by req.prop… no effect. Just default store implemented…

```js
// login.js

let session = new Session(sessionStorage)

function login(req, res, next) {
  if(req.remember) session.store = localStorage
  fetch(toLoginEP)
  if(res.ok) session.update(res)
}
```

But I’m initialise session in separately file.js not in Comp.svelte…

**Comment by Valexr** [comment]
> Testing. Not working for me:
> in login endpoint middleware I trying before fetch set store by req.prop… no effect. Just default store implemented…
> 
> ```js
> // login.js
> 
> let session = new Session(sessionStorage)
> 
> function login(req, res, next) {
>   if(req.remember) session.store = localStorage
>   fetch(toLoginEP)
>   if(res.ok) session.update(res)
> }
> ```
> 
> But I’m initialise session in separately file.js not in Comp.svelte…

Ups... disinformation
